################################################################################
#+
#  Module:	$KSSDIR/qlook2/osiris/Makefile
#
#  Revisions:   
#
#  Author:	Michael McElwain
#
#  Date:	2005/12/20
#
#  Description:	Makefile for OSIRIS specific QL2 files
#-
################################################################################

#  Include files.

INCLUDE	= 

#  C source and object files.
CFLAGS  = 

SOURCE	= 
OBJECT	= 

DIRS	= 

#  Files to make are ...
FILES	= 

#  Files to release are ...
RELFILES = 
RELPRO   = osiris_imag_effwave.pro 

PROSUB = qlook2/configs

#override SYSNAM = kss/qlook2/
#override VERNUM = 1.4

#  Include general make rules (use /etc if no environment variable).

include $(KROOT)/etc/config.mk
