###############################################################################
#+
#  Module:	$KSSDIR/osiris/drs/modules
#
#  Revisions:   
#
#  Author:	Jason Weiss
#
#  Date:	2005/09/20
#
#  Description:	Makefile for DRP modules
#-
###############################################################################

#  Include files.

INCLUDE	= 

#  C source and object files.
CFLAGS  = 

SOURCE	= 
OBJECT	= 

DIRS	= idl_downloads source lib

#  Files to make are ...
FILES	= 

#  Files to release are ...
RELFILES = 

RELDAT   = 
RELPRO   = adjchan_000.pro \
	   badpixnois_000.pro \
	   calibrflux_000.pro \
	   calibrwave_000.pro \
	   cleannoise_000.pro \
	   cleanpsf___000.pro \
	   computspec_000.pro \
	   comtellspe_000.pro \
	   convertpsf_000.pro \
	   corrdisper_000.pro \
	   corrohline_000.pro \
	   corrtellin_000.pro \
	   divblackbo_000.pro \
	   divideflat_000.pro \
	   divstarspe_000.pro \
	   extracsigi_000.pro \
	   extracsigs_000.pro \
	   extractpsf_000.pro \
	   fitdispers_000.pro \
	   glitchid_000.pro \
	   glitchremv_000.pro \
	   interponed_000.pro \
	   intpthreed_000.pro \
	   lineapixel_000.pro \
	   makedarkfr_000.pro \
	   makeflatfi_000.pro \
	   makekskyfr_000.pro \
	   makintfram_000.pro \
	   mkdatacube_000.pro \
	   mkdetrespo_000.pro \
	   mkfluxcalb_000.pro \
	   mkrecmatrx_000.pro \
	   mkrectdark_000.pro \
	   mkwavcalfr_000.pro \
	   mkwavsmo_000.pro \
	   mosaicdith_000.pro \
	   mosaicdpos_000.pro \
	   nrmflxdens_000.pro \
	   nrmflxmagn_000.pro \
	   rmcrosstalk_000.pro \
	   savedatset_000.pro \
	   saveflatfi_000.pro \
	   spatrectif_000.pro \
	   srtrectdat_000.pro \
	   subbackgrd_000.pro \
	   subtracsky_000.pro \
	   subtradark_000.pro \
	   tellcor_000.pro 

PROSUB = odrs/modules

override SYSNAM = kss/osiris/drs/modules/
override VERNUM = 1.4

#  Include general make rules (use /etc if no environment variable).

include $(KROOT)/etc/config.mk
