###############################################################################
#+
#  Module:	$KSSDIR/osiris/drs/modules
#
#  Revisions:   
#
#  Author:	Jason Weiss
#
#  Date:	2005/09/20
#
#  Description:	Makefile for DRP modules
#-
###############################################################################

#  Include files.

INCLUDE	= 

#  C source and object files.
CFLAGS  = 

SOURCE	= 
OBJECT	= 

DIRS	= idl_downloads source

#  Files to make are ...
FILES	= 

#  Files to release are ...
RELFILES = 

RELDAT   = 
RELPRO   = adjchan_000.pro \
	   assembcube_000.pro \
	   calibrwave_000.pro \
	   cleancosmic_000.pro \
           combframes_000.pro \
	   corrtilt_000.pro \
	   divblackbo_000.pro \
	   divideflat_000.pro \
	   divstarspe_000.pro \
	   extracstar_000.pro \
	   fitdispers_000.pro \
	   glitchid_000.pro \
	   linext_000.pro \
	   makedarkfr_000.pro \
	   mkdatacube_000.pro \
	   mkrecmatrx_000.pro \
	   mkrectdark_000.pro \
	   mkwavcalfr_000.pro \
	   mkwavsmo_000.pro \
           mosaic_000.pro \
           mosaicdpos_000.pro \
	   nrmflxdens_000.pro \
	   nrmflxmagn_000.pro \
	   oflipy_000.pro \
	   remhydr_000.pro \
	   rmcrosstalk_000.pro \
	   savedatset_000.pro \
	   saveflatfi_000.pro \
	   spatrectif_000.pro \
	   srtrectdat_000.pro \
	   subtradark_000.pro \
           swapchan_000.pro \
	   scaledskysub_000.pro \
	   addwcs_000.pro \
	   rename_000.pro

PROSUB = odrs/modules

override SYSNAM = kss/osiris/drs/modules/
override VERNUM = 3.2.2 

#  Include general make rules (use /etc if no environment variable).

include $(KROOT)/etc/config.mk
