#
#  Makefile.local
#  OsirisDRP
#
#  Created by Alexander Rudy on 2016-05-04.
#

SOURCE = modules/source
include modules/source/Makefile.local

.PHONY: test

all: $(SOURCE)/libosiris_drp_ext_null.so.0.0
	git submodule init
	git submodule update
	

test: all
	tests/run_tests.sh