###############################################################################
#+
#  Module:	$KSSDIR/osiris/drs/modules/idl_downloads/Makefile
#
#  Revisions:   
#
#  Author:	Jason Weiss
#
#  Date:	2005/09/20
#
#  Description:	Makefile for auxillary idl files for DRP modules
#-
###############################################################################

#  Include files.

INCLUDE	= 

#  C source and object files.
CFLAGS  = 

SOURCE	= 
OBJECT	= 

DIRS	= 

#  Files to make are ...
FILES	= 

#  Files to release are ...
RELFILES = 

RELDAT   = 
RELPRO   = add_fitskwd_to_header.pro \
	   arr_chk.pro \
	   average_frames.pro \
	   blackbody.pro \
	   bool_arr_chk.pro \
	   bool_arr_match.pro \
	   bool_contains_finite.pro \
	   bool_contains_inf.pro \
	   bool_contains_nan.pro \
	   bool_contains_neg.pro \
	   bool_dataset_integrity.pro \
	   bool_dim_match.pro \
	   bool_invert.pro \
	   bool_is_bool.pro \
	   bool_is_byte.pro \
	   bool_is_complex.pro \
	   bool_is_cube.pro \
	   bool_is_defined.pro \
	   bool_is_double.pro \
	   bool_is_float.pro \
	   bool_is_heap.pro \
	   bool_is_image.pro \
	   bool_is_integer.pro \
	   bool_is_obj.pro \
	   bool_is_ptrarr.pro \
	   bool_is_ptr.pro \
	   bool_is_scalar.pro \
	   bool_is_sky.pro \
	   bool_is_string.pro \
	   bool_is_struct.pro \
	   bool_is_vector.pro \
	   bool_pointer_integrity.pro \
	   bool_ptrarr_valid.pro \
	   bool_ptr_cube.pro \
	   bool_ptr_image.pro \
	   bool_ptr_valid.pro \
	   buie_avgclip.pro \
	   break_path.pro \
	   calc_reg_wl_grid.pro \
	   calculate_regular_wavelength_grid.pro \
	   calculate_weight.pro \
	   calibrwave.pro \
	   check_bits.pro \
	   check_fits.pro \
	   check_median.pro \
	   check_module.pro \
	   check_noise.pro \
	   checkvalidity.pro \
	   chktag.pro \
	   clean_op.pro \
	   clean.pro \
           clear_frame.pro \
	   clip_frames.pro \
	   clipimages.pro \
	   clip.pro \
	   cmapply.pro \
           cmset_op.pro \
	   cube2image.pro \
	   cubes_mosaic_cubes.pro \
	   data_valid.pro \
	   daycnv.pro \
	   debug_info.pro \
	   declare_app_constants.pro \
	   define_error_constants.pro \
	   define_module.pro \
	   delete_frame.pro \
	   det2coord.pro \
	   detabify.pro \
	   determine_mosaic_offsets_from_header.pro \
	   div_by_vector.pro \
	   drpxlatefilename.pro \
	   drpXlateFileName.pro \
	   equalize_bak.pro \
	   equalize.pro \
	   error.pro \
	   extbit.pro \
	   extr_horne_1.pro \
	   extr_stellar_spec_2.pro \
	   extr_stellar_spec.pro \
	   filterinfo.pro \
	   findlines_get_index.pro \
	   findlines_get_lamp_status.pro \
	   findlines_new.pro \
	   findlines.pro \
	   findlines_read_calline_file.pro \
	   findlines_x.pro \
	   findlines_y.pro \
	   findspecres.pro \
	   find_with_def.pro \
	   fit_dispersion.pro \
	   fits_close.pro \
	   fitsdir.pro \
	   fits_help.pro \
	   fits_info.pro \
	   fits_open.pro \
	   fits_read.pro \
	   fits_write.pro \
	   fix_nb_scan.pro \
	   frame_op.pro \
	   frame_op_ssr.pro \
	   fxaddpar.pro \
	   fxhmodify.pro \
	   fxhread.pro \
	   fxparpos.pro \
	   fxpar.pro \
	   fxposit.pro \
	   gauss1p.pro \
	   gauss1.pro \
	   gauss2.pro \
	   general_log_name.pro \
	   generate_kernel.pro \
	   get_date.pro \
	   get_filter_param.pro \
	   get_kwd.pro \
	   get_linelist.pro \
	   gettok.pro \
	   headfits.pro \
	   hexpict.pro \
	   ICG_LIB.pro \
	   image_stat_on_rect.pro \
	   img_aperture.pro \
	   img_cube2image.pro \
	   img_lin2dfit2.pro \
	   info.pro \
	   intauxframe_compatibility.pro \
	   interponed.pro \
	   intframe2noise.pro \
	   intframe_translate.pro \
	   int_valid.pro \
	   is_ieee_big.pro \
	   lenslets.pro \
	   linearize.pro \
	   linfitframes.pro \
	   lin_fit_planes.pro \
	   make_dataset_euro3d_compliant.pro \
	   make_det_response.pro \
	   make_euro3d_compliant.pro \
	   make_filename.pro \
	   MakeFileName.pro \
	   makestddrpdata.pro \
           meanclipdrl.pro \
	   median_filter_1d.pro \
	   medianscheck.pro \
	   minmax_2d.pro \
	   mkhdr.pro \
	   moffat.pro \
	   mosaicdith_imag_integrity.pro \
	   mosaicdith_integrity.pro \
	   mosaicdith_spec_integrity.pro \
	   mosaic.pro \
	   mpchilim.pro \
	   mpchitest.pro \
	   mpcurvefit.pro \
	   mpfit2dfun.pro \
	   mpfit2dpeak.pro \
	   mpfitellipse.pro \
	   mpfitexpr.pro \
	   mpfitfun.pro \
	   mpfitpeak.pro \
	   mpfit.pro \
	   mpftest.pro \
	   mpnormlim.pro \
	   mpnormtest.pro \
	   mrd_hread.pro \
	   mrd_skip.pro \
	   my_index.pro \
	   noiseanalysis.pro \
	   onedata.pro \
	   onedatasmall.pro \
	   oneintframeaux.pro \
	   oneintframeauxsmall.pro \
	   oneintframe.pro \
	   oneintframesmall.pro \
	   psf_fit_from_cube.pro \
	   qbit_transform.pro \
	   qbit_translate.pro \
	   rdbv.pro \
	   readfits.pro \
	   replicate_vector.pro \
	   report_success.pro \
	   resize_dataset.pro \
	   save_dataset.pro \
	   search_bad_pixels_via_noise.pro \
	   searchBadPixelsViaNoise.pro \
	   setbit.pro \
	   setfitparm.pro \
	   set_header.pro \
	   sfit_surface.pro \
	   shift_image.pro \
	   shift_object.pro \
	   sigfig.pro \
	   sigma_poly_fit.pro \
	   skysclim.pro \
	   smile.pro \
	   spec_opt_extract_spec_from_cube_simple.pro \
	   strg.pro \
	   strn.pro \
	   strnumber.pro \
           struct_merge.pro \
           struct_trimtags.pro \
	   strwithzeroes.pro \
	   subtract_slice_bg_from_cube.pro \
	   sxaddpar.pro \
	   sxdelpar.pro \
	   sxpar.pro \
	   tnmin.pro \
	   update_dataset_pointer.pro \
	   update_dataset.pro \
	   valid_num.pro \
	   valid.pro \
	   verify_dataset_naxis.pro \
	   verify_naxis.pro \
	   warning.pro \
	   weightedmean.pro \
	   writefits.pro \
	   write_spiffi_cube.pro \
	   zerodata.pro \
	   zerodatasmall.pro \
	   zerointframeaux.pro \
	   zerointframeauxsmall.pro \
	   zerointframe.pro \
	   zerointframesmall.pro \
	   imdisp.pro 

PROSUB = odrs/modules/idl_downloads

override SYSNAM = kss/osiris/drs/modules/idl_downloads/
override VERNUM = 3.2

#  Include general make rules (use /etc if no environment variable).

include $(KROOT)/etc/config.mk
