################################################################################
#+
#  Module:	$KSSDIR/osiris/drs/gui
#
#  Revisions:   
#
#  Author:	Jason Weiss
#
#  Date:	2005/09/20
#
#  Description:	DRS GUI level Makefile for OSIRIS
#-
################################################################################

#  Include files.

INCLUDE	= 

#  C source and object files.
CFLAGS  = 

SOURCE	= 
OBJECT	= 

DIRS	= drpUtil odrfgui classes #drpUtil odrfgui classes

#  Files to make are ...
FILES	= 

#  Files to release are ...
RELFILES  = 

override SYSNAM = kss/osiris/drs/gui/
override VERNUM = 3.0.1

#  Include general make rules (use /etc if no environment variable).

include $(KROOT)/etc/config.mk

