################################################################################
#+
#  Module:	$KSSDIR/qlook2/idl_downloads/Makefile
#
#  Revisions:   
#
#  Author:	Michael McElwain
#
#  Date:	2007/06/12
#
#  Description:	Makefile for QL2 configs
#-
################################################################################

#  Include files.

INCLUDE	= 

#  C source and object files.
CFLAGS  = 

SOURCE	= 
OBJECT	= 

DIRS	= 

#  Files to make are ...
FILES	= 

#  Files to release are ...
RELFILES = 
RELPRO   = aper.pro \
	   cmapply.pro \
	   cmmedian.pro \
	   fits_info.pro \
	   mpfit.pro \
           mpfit2dpeak.pro \
	   mpfit2dfun.pro \
	   mpfitfun.pro \
	   mpfitpeak.pro \
	   sigfig.pro \
	   textbox.pro \
	   tvimage.pro \
	   readfits.pro \

PROSUB = qlook2/idl_downloads

#override SYSNAM = kss/qlook2/
#override VERNUM = 1.4

#  Include general make rules (use /etc if no environment variable).

include $(KROOT)/etc/config.mk
