###############################################################################
#+
#  Module:	$KSSDIR/osiris/drs/gui/odrfgui/templates
#
#  Revisions:   
#
#  Author:	Jason Weiss
#
#  Date:	2005/11/29
#
#  Description:	Makefile for ODRFGUI templates
#-
###############################################################################

#  Include files.

INCLUDE	= 

#  C source and object files.
CFLAGS  = 

SOURCE	= 
OBJECT	= 

DIRS	= 

#  Files to make are ...
FILES	= 

#  Files to release are ...
RELFILES = 

RELDAT   = basicARP_drfTemplate.xml \
	   basicORP_drfTemplate.xml

#override SYSNAM = kss/osiris/drs/gui/odrfgui
#override VERNUM = 1.4

#  Include general make rules (use /etc if no environment variable).

include $(KROOT)/etc/config.mk
