###############################################################################
#+
#  Module:	$KSSDIR/osiris/drs/backbone/SupportFiles
#
#  Revisions:   
#
#  Author:	Jason Weiss
#
#  Date:	2005/09/20
#
#  Description:	Makefile for DRP backbone support files (RPBconfig.xml)
#-
###############################################################################

#  Include files.

INCLUDE	= 

#  C source and object files.
CFLAGS  = 

SOURCE	= 
OBJECT	= 

DIRS	= 

#  Files to make are ...
FILES	= 

#  Files to release are ...
RELFILES = 

RELDAT   = osirisDRPConfigFile \
	   RPBconfig.xml

override SYSNAM = kss/osiris/drs/backbone/
override VERNUM = 4.1 

#  Include general make rules (use /etc if no environment variable).

include $(KROOT)/etc/config.mk
