################################################################################
#+
#  Module:	$KSSDIR/osiris/drs/gui/classes/Makefile
#
#  Revisions:   
#
#  Author:	Jason Weiss
#
#  Date:	
#
#  Description:	
#-
################################################################################

#  Include files.

INCLUDE	= 

#  C source and object files.
CFLAGS  = 

SOURCE	= 
OBJECT	= $(wildcard *.jar)

DIRS	= 

#  Files to make are ...
FILES	= 

#  Files to release are ...
RELFILES  = $(OBJECT)

#  This is a release point. Define version macros to override values inherited
#  from the environment.

#  Include general make rules (use /etc if no environment variable).

include $(KROOT)/etc/config.mk

clean:
	/usr/bin/rm -f *.jar
