###############################################################################
#+
#  Module:	$KSSDIR/osiris/drs/data
#
#  Revisions:   
#
#  Author:	Jason Weiss
#
#  Date:	2005/09/20
#
#  Description:	Makefile for DRP data files
#-
###############################################################################

#  Include files.

INCLUDE	= 

#  C source and object files.
CFLAGS  = 

SOURCE	= 
OBJECT	= 

DIRS	= 

#  Files to make are ...
FILES	= 

#  Files to release are ...
RELFILES = 

RELDAT   = osiris_cal_line.list \
	   osiris_filter_info.list \
	   osiris_wave_coeffs.fits \
	   osiris_wave_coeffs_050222-060222.fits \
	   osiris_wave_coeffs_060223-091004.fits \
	   osiris_wave_coeffs_091005-120103.fits \
	   osiris_wave_coeffs_120104-121109.fits \
	   osiris_wave_coeffs_121110-151231.fits

override SYSNAM = kss/osiris/drs/data/
override VERNUM = 4.1 

#  Include general make rules (use /etc if no environment variable).

include $(KROOT)/etc/config.mk
