################################################################################
#+
#  Module:	$KSSDIR/qlook2/configs/Makefile
#
#  Revisions:   
#
#  Author:	Michael McElwain
#
#  Date:	2005/03/23
#
#  Description:	Makefile for QL2 configs
#-
################################################################################

#  Include files.

INCLUDE	= 

#  C source and object files.
CFLAGS  = 

SOURCE	= 
OBJECT	= 

DIRS	= 

#  Files to make are ...
FILES	= 

#  Files to release are ...
RELFILES = 
RELPRO   = osiris_im_cfg.pro \
           osiris_frp_cfg.pro \
	   osiris_online_cfg.pro \
	   osiris_spec_cfg.pro 

PROSUB = qlook2/configs

#override SYSNAM = kss/qlook2/
#override VERNUM = 1.4

#  Include general make rules (use /etc if no environment variable).

include $(KROOT)/etc/config.mk
