#!/bin/csh -f

if ( ! -d "$DRF_QUEUE_DIR" ) then
    echo "Error: $DRF_QUEUE_DIR does not exist or is not a directory"
    exit 1
endif

if ( ! -e "$1" ) then
    echo "Error: $1 does not exist or is not a file"
    exit 1
endif

if ( ! -w "$DRF_QUEUE_DIR" ) then
    echo "Error: insufficient permissions to write to $DRF_QUEUE_DIR"
    exit 1
endif

cp "$1" "$DRF_QUEUE_DIR/$2.$1:r.waiting"

