#!/bin/csh -f
#
# Name:
#     osiris_drp_32bit
#
# Purpose:
#     DRP default is now 64-bit.  For older CFITSIO installs, the DRP must 
#     still be run in 32-bit mode
# 
# Modifications:
#     2013 jul 28 jlyke Original
#
#----------------------------------------------------
#
# Default Makefile
set mfile = local_Makefile32

# Check for OSIRIS_ROOT envar, prompt for dir if not set
if ( $?OSIRIS_ROOT ) then
  set mydir = $OSIRIS_ROOT/modules/source
else
  echo "OSIRIS_ROOT envar is not set"
  echo -n "Enter the directory with OSIRIS DRP C code (should end with modules/source)"
set mydir = $<
endif

set pwd = `pwd`
# Check for existance of dir
if ( -d $mydir ) then
  cd $mydir
  \rm *.o
  \rm libosiris*
  if ( -e $mfile ) then
    make -f $mfile
    if ( $status == 0 ) then
      echo "Make successful"
    else
      echo "Make error"
    endif
  else
    echo "$mfile does not exist"
  endif
else
  echo "$mydir does not exist"
  exit 1
endif

exit 0
    

