#!/bin/csh -f
#
# Stand alone script to launch Quicklook v2.0 IDL program.
#
# James Larkin 1/30/98
# modified for host 'nirspec' by George Brims 2/26/98
# Completely changed for batch execution instead of
# RPC communication. 3/1/98.
# modified to run outside of qlook dir by setting env 
#    variable -- Jason L. Weiss 02/03/00
# modified to run in an xterm -- Michael W. McElwain 03/13/06


# set $QL_FILEDIR if it does not already exists
#setenv QL_FILEDIR $OSIRIS_ROOT/ql2
#set file_status=`echo $QL_FILEDIR`
#echo $file_status
#set display=$1
#echo $display



#echo $#argv
#echo $*

# Pass in an argument which tells you which configuration file you
# want to use.  Then put in a switch right here that calls the appropriate
# startup file.  Count the number of arguments, if there is only 1, then you
# should have a default startup file.  Do some error checking to see if there
# is a 2nd parameter that doesn't match any of the startup files.

# start ql2
if ($#argv > 0) then

    xterm +ls -sb -sl 5000 -T 'ql2' -e idl $OSIRIS_ROOT/ql2/qlook2_startup
    
endif
