###############################################################################
#+
#  Module:	$KSSDIR/osiris/drs/backbone
#
#  Revisions:   
#
#  Author:	Jason Weiss
#
#  Date:	2005/09/20
#
#  Description:	Makefile for DRP backbone
#-
###############################################################################

#  Include files.

INCLUDE	= 

#  C source and object files.
CFLAGS  = 

SOURCE	= 
OBJECT	= 

DIRS	= SupportFiles

#  Files to make are ...
FILES	= 

#  Files to release are ...
RELFILES = 

RELDAT   = 
RELPRO   = drpBackbone__define.pro \
	   drpConfigParser__define.pro \
	   drpDRFParser__define.pro \
	   drpDRFPipeline__define.pro \
	   drpMain.pro \
	   drpPipeline__define.pro \
	   drpRun.pro \
	   osiris_drp_backbone_startup.pro


PROSUB = odrs/backbone

override SYSNAM = kss/osiris/drs/backbone/
override VERNUM = 2.2.1 

#  Include general make rules (use /etc if no environment variable).

include $(KROOT)/etc/config.mk
